default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  timeout: 5000

development:
  <<: *default
  database: asashibu-api_dev

test:
  <<: *default
  database: asashibu-api_test

production:
  <<: *default
  database: asashibu-api_production
